language: python
python:
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
addons:
  apt:
    packages:
    - sshpass
install:
  - pip install -r requirements.txt
script: pytest
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -p $EC2_TRAVIS_PW ssh $EC2_TRAVIS_SERVER ./deploy
  on:
    branch: master
