language: python
python:
  - "3.9"
before_install:
  - python -m pip install --upgrade pip
addons:
  apt:
    packages:
    - sshpass
install:
  - pip install -r requirements.txt
script: pytest
deploy:
  provider: script
  skip_cleanup: true
  script: sshpass -e ssh -o StrictHostKeyChecking=no $EC2_TRAVIS_SERVER 'sudo bash deploy'
  on:
    branch: master
after_success:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $WEBHOOK_URL
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $WEBHOOK_URL
